export const themesCollection = [
  { name: 'default',                 type: 'light' },
  { name: '3024-day',                type: 'light' },
  { name: '3024-night',              type: 'dark'  },
  { name: 'abcdef',                  type: 'dark'  },
  { name: 'ambiance-mobile',         type: 'light' },
  { name: 'ambiance',                type: 'dark'  },
  { name: 'base16-dark',             type: 'dark'  },
  { name: 'base16-light',            type: 'light' },
  { name: 'bespin',                  type: 'dark'  },
  { name: 'blackboard',              type: 'dark'  },
  { name: 'cobalt',                  type: 'dark'  },
  { name: 'colorforth',              type: 'dark'  },
  { name: 'dracula',                 type: 'dark'  },
  { name: 'eclipse',                 type: 'light' },
  { name: 'elegant',                 type: 'light' },
  { name: 'erlang-dark',             type: 'dark'  },
  { name: 'hopscotch',               type: 'dark'  },
  { name: 'icecoder',                type: 'dark'  },
  { name: 'isotope',                 type: 'dark'  },
  { name: 'lesser-dark',             type: 'dark'  },
  { name: 'liquibyte',               type: 'dark'  },
  { name: 'material',                type: 'dark'  },
  { name: 'mbo',                     type: 'dark'  },
  { name: 'mdn-like',                type: 'light' },
  { name: 'midnight',                type: 'dark'  },
  { name: 'monokai',                 type: 'dark'  },
  { name: 'neat',                    type: 'light' },
  { name: 'neo',                     type: 'light' },
  { name: 'night',                   type: 'dark'  },
  { name: 'paraiso-dark',            type: 'dark'  },
  { name: 'paraiso-light',           type: 'light' },
  { name: 'pastel-on-dark',          type: 'dark'  },
  { name: 'railscasts',              type: 'dark'  },
  { name: 'rubyblue',                type: 'dark'  },
  { name: 'seti',                    type: 'dark'  },
  { name: 'solarized',               type: 'light' },
  { name: 'the-matrix',              type: 'dark'  },
  { name: 'tomorrow-night-bright',   type: 'dark'  },
  { name: 'tomorrow-night-eighties', type: 'dark'  },
  { name: 'ttcn',                    type: 'light' },
  { name: 'twilight',                type: 'dark'  },
  { name: 'vibrant-ink',             type: 'dark'  },
  { name: 'xq-dark',                 type: 'dark'  },
  { name: 'xq-light',                type: 'light' },
  { name: 'yeti',                    type: 'light' },
  { name: 'zenburn',                 type: 'dark'  },
];

export const themes = themesCollection.map(({ name }) => name);

export const themesType = themesCollection.reduce((obj, { name, type }) => {
  obj[name] = type;
  return obj;
},{})
